/* Wein-Berater Service Worker — wein-berater-v5_50 */
const CACHE = "wein-berater-v5_50";
const ASSETS = [
  "./",
  "./index.html",
  "./wein-berater-v5_50.html",
  "./manifest.json",
  "aromen/Akazie.png",
  "aromen/Ananas.png",
  "aromen/Anis.png",
  "aromen/Apfel.png",
  "aromen/Aprikose.png",
  "aromen/Asche.png",
  "aromen/Banane.png",
  "aromen/Bergamotte.png",
  "aromen/Bergkräuter.png",
  "aromen/Bienenwachs.png",
  "aromen/Birne.png",
  "aromen/Bittermandel.png",
  "aromen/Bitterschokolade.png",
  "aromen/Bleistiftmine.png",
  "aromen/Blüten.png",
  "aromen/Bonbon.png",
  "aromen/Brioche.png",
  "aromen/Brombeere.png",
  "aromen/Brombeermarmelade.png",
  "aromen/Butter.png",
  "aromen/Cassis.png",
  "aromen/Cranberry.png",
  "aromen/Curry.png",
  "aromen/Erdbeere.png",
  "aromen/Eukalyptus.png",
  "aromen/Feige.png",
  "aromen/Fenchel.png",
  "aromen/Feuerstein.png",
  "aromen/Garrigue-Kräuter.png",
  "aromen/Garrigue.png",
  "aromen/Geißblatt.png",
  "aromen/Gewürz.png",
  "aromen/Gewürze.png",
  "aromen/Granatapfel.png",
  "aromen/Grapefruit.png",
  "aromen/Graphit.png",
  "aromen/Gras.png",
  "aromen/Haselnuss.png",
  "aromen/Hefe.png",
  "aromen/Heu.png",
  "aromen/Himbeerbonbon.png",
  "aromen/Himbeere.png",
  "aromen/Holunder.png",
  "aromen/Holunderblüte.png",
  "aromen/Honig.png",
  "aromen/Honigmelone.png",
  "aromen/Hülsenfrüchte.png",
  "aromen/Ingwer.png",
  "aromen/Jod.png",
  "aromen/Johannisbeere.png",
  "aromen/Kakao.png",
  "aromen/Kamille.png",
  "aromen/Kirsche.png",
  "aromen/Kräuter.png",
  "aromen/Kräuter_der_Provence.png",
  "aromen/Kräutertee.png",
  "aromen/Lakritz.png",
  "aromen/Lanolin.png",
  "aromen/Lavendel.png",
  "aromen/Lebkuchengewürz.png",
  "aromen/Leder.png",
  "aromen/Limette.png",
  "aromen/Litschi.png",
  "aromen/Mandel.png",
  "aromen/Mango.png",
  "aromen/Maracuja.png",
  "aromen/Mineral.png",
  "aromen/Minze.png",
  "aromen/Mirabelle.png",
  "aromen/Mokka.png",
  "aromen/Muskat.png",
  "aromen/Nelke.png",
  "aromen/Nuss.png",
  "aromen/Orangenblüte.png",
  "aromen/Orangenmarmelade.png",
  "aromen/Orangenzeste.png",
  "aromen/Paprika.png",
  "aromen/Pfeffer.png",
  "aromen/Pfirsich.png",
  "aromen/Pflaume.png",
  "aromen/Quitte.png",
  "aromen/Rauch.png",
  "aromen/Rhabarber.png",
  "aromen/Ribisel__Johannisbeere_.png",
  "aromen/Rose.png",
  "aromen/Rosenblüte.png",
  "aromen/Rosenblüten.png",
  "aromen/Rosine.png",
  "aromen/Rosmarin.png",
  "aromen/Salz.png",
  "aromen/Sauerkirsche.png",
  "aromen/Schokolade.png",
  "aromen/Schwarzkirsche.png",
  "aromen/Stachelbeere.png",
  "aromen/Stein.png",
  "aromen/Steinfrucht.png",
  "aromen/Steinobst.png",
  "aromen/Tabak.png",
  "aromen/Teer.png",
  "aromen/Toast.png",
  "aromen/Tomatenblatt.png",
  "aromen/Trüffel.png",
  "aromen/Vanille.png",
  "aromen/Veilchen.png",
  "aromen/Waldboden.png",
  "aromen/Walderdbeere.png",
  "aromen/Walnuss.png",
  "aromen/Wassermelone.png",
  "aromen/Weichsel.png",
  "aromen/Weintraube.png",
  "aromen/Wiesenblumen.png",
  "aromen/Wildaromen.png",
  "aromen/Zedernholz.png",
  "aromen/Zitrone.png",
  "aromen/Zitronencreme.png",
  "aromen/Zitrus.png",
  "aromen/dunkle_Kirsche.png",
  "aromen/erdige_Noten.png",
  "aromen/feuchter_Stein.png",
  "aromen/frisch_geschnittenes_Gras.png",
  "aromen/frische_Kräuter.png",
  "aromen/frische_Traube.png",
  "aromen/gelber_Apfel.png",
  "aromen/getrocknete_Kräuter.png",
  "aromen/grüne_Birne.png",
  "aromen/grüne_Kräuter.png",
  "aromen/grüne_Mandel.png",
  "aromen/grüne_Paprika.png",
  "aromen/grüner_Apfel.png",
  "aromen/kandierte_Frucht.png",
  "aromen/mediterrane_Kräuter.png",
  "aromen/nasse_Wolle.png",
  "aromen/reifer_Apfel.png",
  "aromen/rote_Beeren.png",
  "aromen/rote_Johannisbeere.png",
  "aromen/rote_Kirsche.png",
  "aromen/schwarzer_Pfeffer.png",
  "aromen/weiße_Blüten.png",
  "aromen/weiße_Kirsche.png",
  "aromen/weißer_Pfeffer.png",
  "aromen/weißer_Pfirsich.png"
];
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((keys) =>
    Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
  ).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request).then((hit) => {
    const net = fetch(e.request).then((res) => {
      if (res && res.status === 200 && res.type === "basic") {
        const copy = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy));
      }
      return res;
    }).catch(() => hit);
    return hit || net;
  }));
});
